name: gsheet.action test
on: 
  workflow_dispatch:
    

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - id: 'update_worksheet'
        uses: jroehl/gsheet.action@v2.0.0 # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: ${{ secrets.BLOG_SUBMISSIONS_SPREADSHEET_ID }}
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "getData", "args": { "range": "'Form responses 1'!A2:B3" } }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - name: dump_results
        env:
          #  the output of the action can be found in ${{ steps.update_worksheet.outputs.results }}
          RESULTS: ${{ steps.update_worksheet.outputs.results }}
        run: echo "$RESULTS" > results.json
      - name: Upload results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: results-file
          path: results.json
        
